# 服务地址端口
ip=127.0.0.1
port=8881
# 用户信息
coserial=88888888000000000000000000000000
userial=04d18b7a2c4e1000
user=gjq
token=a3b18d2b46b9d086e1b581deb1ae8da990c1da09

# 语言 zh_CN\zh_HK\en
language=zh_CN
# 报表title
cotitle=Aseit
# 报告存放目录
report=c:/guo/TestJadeClient/report/
root=c:/TestJadeClient/case
# 超时时间(秒)
timeout=120