cc.ip=47.97.28.98
cc.port=7788
es.port=8881
uc.ip=127.0.0.1

accessKey=ff4ff0b2e1974c3e
secretKey=748089da5a5b4f42aaa69115ddf2add4

# 字幕默认设置
Caption.captionDivStyle=left:0px;top:94%;width:100%;height:42px;position: absolute;z-index:9999999; display: block;text-align: center;
Caption.captionStyle=font-size:30px;color:#fef4e9; background: #f78d1d;padding-left:18px;padding-right:18px;display: inline-block;

# 高亮设置
HighLight.specialEffect=1

# 声音转换app设置
voice.provider=baidu
voice.baidu.APP_ID= 10931148
voice.baidu.API_KEY=pGkLGYgAQ1ZZ5QZb5QvDioIb
voice.baidu.SECRET_KEY=fc85e55dc2adb17bba3a9be876f4f5d3

# 声音效果设置
voice.baidu.speed=4
voice.baidu.pitch=5
voice.baidu.volume=5
voice.baidu.person=3

# 视频默认存放路径
Dv.url=c:/dd
# 文件输入输出默认存放路径
file.inpath = D:/V1.0.5/web/html/files/in
file.outpath = D:/V1.0.5/web/html/files/out
file.tmppath = D:/V1.0.5/web/html/files/tmp
file.cache = cache/


